# Generated by Django 5.1.3 on 2024-11-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.TextField(max_length=255)),
                ('calorias', models.IntegerField()),
                ('proteina', models.FloatField()),
                ('carboidrato', models.FloatField()),
                ('gordura', models.FloatField()),
                ('sodio', models.FloatField()),
                ('acucar', models.FloatField()),
                ('sabores', models.TextField(max_length=255)),
            ],
        ),
    ]
