# Generated by Django 5.1.3 on 2024-11-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='carboidrato',
            new_name='carboidratos',
        ),
    ]
