# Generated by Django 5.1.3 on 2024-11-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_web', '0002_rename_carboidrato_produto_carboidratos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='acucar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='carboidratos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='gordura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='proteina',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sabores',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sodio',
            field=models.IntegerField(),
        ),
    ]
